imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
      engines: ['php']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        #options:
            #sslmode: require

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        
doctrine_migrations:
    table_name: migrations

#jms_serializer:
#    metadata:
##        cache: none
##        cache: file
#        debug: "%kernel.debug%"

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
            
services:
    logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments:
        - application.api
        - null
        - null
        - ""
        - 1
    line_formatter:
        class: Monolog\Formatter\LineFormatter


monolog:
   handlers:
       main:
           type: stream
           path: %log_path%
           level: %log_level%
           formatter: logstash_formatter



