services:
    kernel.listener.responseConverter:
        class: AppBundle\EventListener\RestInputOuputFormatter
        arguments: [ @serializer, @logger, ["json"], "json", "%kernel.debug%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }            
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }      
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }      
    em:
        alias: doctrine.orm.entity_manager
    doctrine.listener:
        class: AppBundle\EventListener\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
    app.service.user_registration_service:
        class: AppBundle\Service\UserRegistrationService
        arguments: [@doctrine.orm.entity_manager]

    monolog.processor.add_request_id:
        class: AppBundle\Service\RequestIdLoggerProcessor
        arguments:  [ @service_container ]
        tags:
              - { name: monolog.processor, method: processRecord }

    app.repository.report_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Report\Report

    app.repository.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    app.repository.client_repository:
        class: Doctrine\ORM\EntiryReposotory
        factory:  ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Client

    app.service.stats_service:
        class: AppBundle\Service\StatsService
        arguments: ["@app.repository.user_repository", "@app.service.report_service"]

    app.service.report_service:
        class: AppBundle\Service\ReportService
        arguments:
            - "@app.repository.report_repository"
            - "@app.service.client_service"
            - "@serializer"

    app.service.client_service:
        class:  AppBundle\Service\ClientService
        arguments:
            - "@app.repository.client_repository"

    app.controller.report_controller:
        class: AppBundle\Controller\Report\ReportController
        lazy:  true
        arguments:
            - "@app.service.report_service"
        calls:
            - [setContainer, ["@service_container"]]

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    jms_serializer.unserialize_object_constructor:
        class: AppBundle\Serializer\ObjectConstructor
