<?php

namespace AppBundle\Entity\Repository;

use AppBundle\DTO\DeputyDto;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractEntityRepository
{
    public function getDtoById($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT NEW AppBundle\DTO\DeputyDto(d.id, d.firstname, d.lastname, d.email, d.roleName, d.addressPostcode, d.ndrEnabled) FROM AppBundle\Entity\User d WHERE d.id=?1');
        $query->setParameter(1, $id);

        return $query->getSingleResult();
    }
}
