services:
  AppBundle\v2\Assembler\ClientAssembler:
    class: AppBundle\v2\Assembler\ClientAssembler

  AppBundle\v2\Assembler\DeputyAssembler:
    class: AppBundle\v2\Assembler\DeputyAssembler
    arguments:
      - '@AppBundle\v2\Assembler\ClientAssembler'

