services:

  AppBundle\v2\Registration\Controller\LayDeputyshipUploadController:
    class: AppBundle\v2\Registration\Controller\LayDeputyshipUploadController
    arguments:
      - '@AppBundle\v2\Registration\DataCompression'
      - '@AppBundle\v2\Registration\Assembler\LayDeputyshipDtoCollectionAssembler'
      - '@AppBundle\v2\Registration\Uploader\CasRecLayDeputyshipUploader'
    public: true

  AppBundle\v2\Registration\Assembler\LayDeputyshipDtoAssembler:
    class: AppBundle\v2\Registration\Assembler\LayDeputyshipDtoAssembler

  AppBundle\v2\Registration\Assembler\LayDeputyshipDtoCollectionAssembler:
    class: AppBundle\v2\Registration\Assembler\LayDeputyshipDtoCollectionAssembler
    arguments:
      - '@AppBundle\v2\Registration\Assembler\LayDeputyshipDtoAssembler'

  AppBundle\v2\Registration\DataCompression:
    class: AppBundle\v2\Registration\DataCompression

  AppBundle\v2\Registration\SelfRegistration\Factory\CasRecFactory:
    class: AppBundle\v2\Registration\SelfRegistration\Factory\CasRecFactory
    arguments:
      - '@validator'
      - '@app.service.date_time_provider'

  AppBundle\v2\Registration\Uploader\CasRecLayDeputyshipUploader:
    class: AppBundle\v2\Registration\Uploader\CasRecLayDeputyshipUploader
    arguments:
      - '@em'
      - '@AppBundle\Entity\Repository\ClientRepository'
      - '@opg_digideps.report_service'
      - '@AppBundle\v2\Registration\SelfRegistration\Factory\CasRecFactory'

