services:
  UserRepository:
    class: AppBundle\Entity\User
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\User

  AppBundle\v2\Repository\DeputyRepository:
    class: AppBundle\v2\Repository\DeputyRepository
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@UserRepository'
      - '@AppBundle\v2\Assembler\DeputyAssembler'
